# Generated by Django 5.2.3 on 2025-06-21 07:45

from django.db import migrations

import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_role"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", users.models.CustomUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
    ]
