# Generated by Django 5.2.3 on 2025-06-21 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingrecipient",
            options={
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылок",
            },
        ),
        migrations.AlterModelOptions(
            name="messagelog",
            options={
                "managed": True,
                "verbose_name": "Журнал сообщений",
                "verbose_name_plural": "Журналы сообщений",
            },
        ),
    ]
