# Generated by Django 5.2.3 on 2025-06-21 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_alter_mailingrecipient_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [("can_disable_mailing", "Может отключать рассылки")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
